Fix for #4, #5, #6
IBM/ibm-spectrum-lsf-rtm-server pull request #8
Opened 2022-09-24 21:51 UTC by sbuser-git

Resolved #XXXX.

2022-09-26 13:36 UTC, TheWitness commented on cacti/plugins/benchmark/grid_benchmark_jobs.php
> +							$clusters = db_fetch_assoc('SELECT * FROM grid_clusters ORDER BY clustername');
This bit should be backed out.

2022-09-26 13:37 UTC, TheWitness requested changes
I believe that one line that I commented should be backed out, but the rest looks good.

2022-09-30 23:00 UTC, sbuser-git commented on cacti/plugins/benchmark/grid_benchmark_jobs.php
> +							$clusters = db_fetch_assoc('SELECT * FROM grid_clusters ORDER BY clustername');
Thanks, will back it out.

2022-10-23 16:31 UTC, ddb4github commented
1. #5 diff is OK for me,  suggest to rename funcname `stopRKey` because it is not related to "Retrun" key now.
2. Why change `$job_exitinfo` to `-1`,  function `getExceptionStatus` has avoid to display `TERM_UNKNOWN`.
3. #4 diff: How about use Cacti core function `check_changed` in diff of function `process_request_var`
4. #9 diff is OK for me
5. #6 diff is OK for me

2022-11-22 18:01 UTC, TheWitness commented
@ddb4github, since the only thing that invalidates the "benchmark_id" is the "clusterid" change, I'm okay using that function as well.  It's your call.  You should be able to make the edits required to complete the merge right?

2022-12-01 23:14 UTC, sbuser-git commented
Add 4 commits from Larry for: patch that disables the query cache for the Cacti Data Collectors - https://github.com/IBM/ibm-spectrum-lsf-rtm-server/issues/10

2023-01-11 16:01 UTC, merged